services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Wexample\SymfonyAccounting\Service\:
        resource: '../../Service/*'
        tags: ['controller.service_arguments']
